[pytest]
asyncio_mode = auto
testpaths = tests
filterwarnings =
    error
    ignore::DeprecationWarning:vectorbt.*
    ignore::DeprecationWarning:pandas.*
    ignore::DeprecationWarning:pydantic.*
    ignore::PendingDeprecationWarning:vectorbt.*
